name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
    - name: wasm-pack-action
      uses: jetli/wasm-pack-action@v0.3.0
    - name: WASM Build
      run: wasm-pack build -- --features wee_alloc
    - name: Outpt WASM Package
      uses: actions/upload-artifact@v2
      with:
        name: newton-2d
        path: /home/runner/work/newton-2d/newton-2d/pkg
